const resObj = [
  {
    id: 1,
    name: "Meghana Foods",
    cuisines: ["Biryani", "North - Indian", "Mughal"],
    avgRating: 4.5,
    estinameDeliveryTime: "30 min",
    costForTwo: 400,
    cloudinaryImageId: "e0vvulfbahjxjz6k4uwi",
  },
  {
    id: 2,
    name: "Burger Singh(Big Punjabi Burgers)",
    cuisines: [
      "Burgers",
      "Snacks",
      "Fast Food",
      "Indian",
      "American",
      "Beverages",
      "Desserts",
    ],
    avgRating: 4.4,
    estinameDeliveryTime: "25 min",
    costForTwo: 300,
    cloudinaryImageId: "972a37599772cdc7df93a0855ad87591",
  },
  {
    id: 3,
    name: "Mr. Brown - Danbro",
    cuisines: [
      "Bakery",
      "Cakes & Pastries",
      "Snacks",
      "Italian",
      "Pizzas",
      "Burgers",
      "Beverages",
      "Continental",
      "Desserts",
    ],
    avgRating: 4.2,
    estinameDeliveryTime: "32 min",
    costForTwo: 500,
    cloudinaryImageId: "2c469b5d88f84b7495b9825d06e4bb9b",
  },
  {
    id: 4,
    name: "ENSO - Sourdough Pizza by Nomad",
    cuisines: ["Pizzas", "Fast Food", "Desserts", "Salads", "Beverages"],
    avgRating: 3.9,
    estinameDeliveryTime: "40 min",
    costForTwo: 700,
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/9/411f8ce4-9f3c-4e9e-b9c0-802569b2b0a7_866120.jpg",
  },
  {
    id: 5,
    name: "The Dessert Zone",
    cuisines: ["Bakery", "Desserts", "Ice Cream", "Beverages", "Cakes"],
    avgRating: 3.3,
    estinameDeliveryTime: "20 min",
    costForTwo: 250,
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/7/14/87163076-ee61-46fb-95df-e4ffb770a008_923235.jpg",
  },
  {
    id: 6,
    name: "Bro And Brothers",
    cuisines: ["Chinese", "Indian", "Snacks"],
    avgRating: 3.0,
    estinameDeliveryTime: "28 min",
    costForTwo: 350,
    cloudinaryImageId: "c831da8c67324cc6fcd6345ba60e453b",
  },
  {
    id: 7,
    name: "Pandit Ji Ka Dhaba And Family Restaurant",
    cuisines: ["North Indian", "Thalis", "Chinese", "Snacks"],
    avgRating: 3.1,
    estinameDeliveryTime: "57 min",
    costForTwo: 300,
    cloudinaryImageId: "ltunssdojzu8wrnjnypf",
  },
  {
    id: 8,
    name: "Royal Train cuisines",
    cuisines: [
      "North Indian",
      "Bakery",
      "Chinese",
      "South Indian",
      "Pizzas",
      "Beverages",
      "Desert ",
    ],
    avgRating: 4.0,
    estinameDeliveryTime: "45 min",
    costForTwo: 600,
    cloudinaryImageId: "72e6887f212e1946e6bd05371a749339",
  },
  {
    id: 9,
    name: "KFC",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    avgRating: 4.1,
    estinameDeliveryTime: "35 min",
    costForTwo: 450,
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/3/f1725506-fc76-4b59-a234-356b7fd46b80_1110696.jpg",
  },
];

export default resObj;
